Models/DailyQuote.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyPerformanceReportAuto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DailyQuote
    {
        public int Id { get; set; }
        public string QuoteSource { get; set; }
        public string QuoteType { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        public string Value { get; set; }
        public string Comments { get; set; }
    }
}

Controllers/DailyQuotesController.cs
using DailyPerformanceReportAuto.Models;
using DailyPerformanceReportAuto.ViewModel;
using RazorEngine.Templating;
using RazorEngine;
using RazorEngine.Text;
using RazorEngine.Configuration;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;


namespace DailyPerformanceReportAuto.Controllers
{

     public class DailyQuotesController : Controller
        {

        DailyPerformanceReportDbEntities1 db = new DailyPerformanceReportDbEntities1();
            private List<string> _CTopQuote = new List<string>();
            private List<string> _Dstring = new List<string>();

            // GET: DailyQuotes
            public ActionResult Index()
            {
                ViewBag.QSourceList = GetQuoteSource();
                return View();
            }

            [HttpPost]
            public ActionResult IndexList(string _source, string _datestring)
            {
                DateTime date;

                if (String.IsNullOrEmpty(_datestring))
                {
                    date = DateTime.Today.Date;
                }
                else
                {
                    date = Convert.ToDateTime(_datestring);
                }
                return PartialView("_DisplayQuote", db.DailyQuotes.Where(x => x.QuoteSource == _source && x.Date == date).ToList());
            }

            public ActionResult IndexListToday()
            {
                DateTime _date = DateTime.Today.AddDays(-1).Date;

                return PartialView("_DisplayQuote", db.DailyQuotes.Where(x => x.Date == _date));
            }

            // GET: DailyQuotes/Details/5
            public ActionResult Details(int? id)
            {

            if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                DailyQuote dailyQuote = db.DailyQuotes.Find(id);

                if (dailyQuote == null)
                {
                    return HttpNotFound();
                }

                return View(dailyQuote);
            }

        // GET: DailyQuotes/Create
        public ActionResult Create()
        {
            ViewBag.QSourceList = GetQuoteSource();
            return View();
        }

        // POST: DailyQuotes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,QuoteSource,QuoteType,Date,Value,Comments,TQValue,TQComments,PQValue,TopQValue,TopQComments,PQComments,QBValue,QBComments ,TopQuote,TopQuoteComments,TopQuoteHI,TopQuoteHIComments,TopQuoteQ,TopQuoteQComments,ClickThrough,ClickThroughComments,TotalQueries,TotalQuotesReturned,TotalClicks,ProviderQuoteRate,FilteredQuotes,TotalQueriesComments,TotalQuotesReturnedComments,TotalClicksComments,ProviderQuoteRateComments,FilteredQuotesComments,TopQuotes,TopQuotesComments")] DailyQuoteTable dailyQuote)
        {
            if (ModelState.IsValid)
            {
                if (dailyQuote.QuoteSource == "Confused" || dailyQuote.QuoteSource == "Go Compare")
                {
                    DailyQuote newQuote = new DailyQuote();
                    newQuote.Date = dailyQuote.Date;
                    newQuote.QuoteSource = dailyQuote.QuoteSource;

                    newQuote.QuoteType = "Total Quotes";
                    newQuote.Value = dailyQuote.TQValue;
                    newQuote.Comments = dailyQuote.TQComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Partner Quotes";
                    newQuote.Value = dailyQuote.PQValue;
                    newQuote.Comments = dailyQuote.PQComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Top Quote";
                    newQuote.Value = dailyQuote.TopQValue;
                    newQuote.Comments = dailyQuote.TopQComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Top Quotes Q %";
                    newQuote.Value = dailyQuote.TopQuoteQ;
                    newQuote.Comments = dailyQuote.TopQuoteQComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Top Quotes HI %";
                    newQuote.Value = dailyQuote.TopQuoteHI;
                    newQuote.Comments = dailyQuote.TopQuoteHIComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();


                    newQuote.QuoteType = "Quotes Blocked %";
                    newQuote.Value = dailyQuote.QBValue;
                    newQuote.Comments = dailyQuote.QBComments;
                    db.DailyQuotes.Add(newQuote);

                    db.SaveChanges();

                }
                if (dailyQuote.QuoteSource == "Compare The Market")
                {
                    DailyQuote newQuote = new DailyQuote();
                    newQuote.Date = dailyQuote.Date;
                    newQuote.QuoteSource = dailyQuote.QuoteSource;

                    newQuote.QuoteType = "Consumer Enquiries";
                    newQuote.Value = dailyQuote.TQValue;
                    newQuote.Comments = dailyQuote.TQComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Prices Presented";
                    newQuote.Value = dailyQuote.PQValue;
                    newQuote.Comments = dailyQuote.PQComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();
                    newQuote.QuoteType = "Prices Presented @P1";
                    newQuote.Value = dailyQuote.TopQValue;
                    newQuote.Comments = dailyQuote.TopQComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Click Through (PCTs)";
                    newQuote.Value = dailyQuote.ClickThrough;
                    newQuote.Comments = dailyQuote.ClickThroughComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Top Quotes %";
                    newQuote.Value = dailyQuote.TopQuote;
                    newQuote.Comments = dailyQuote.TopQuoteComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();


                    newQuote.QuoteType = "Quotes Declined %";
                    newQuote.Value = dailyQuote.QBValue;
                    newQuote.Comments = dailyQuote.QBComments;
                    db.DailyQuotes.Add(newQuote);

                    db.SaveChanges();
                }
                if (dailyQuote.QuoteSource == "Money Supermarket")
                {
                    DailyQuote newQuote = new DailyQuote();
                    newQuote.Date = dailyQuote.Date;
                    newQuote.QuoteSource = dailyQuote.QuoteSource;

                    newQuote.QuoteType = "Total Queries";
                    newQuote.Value = dailyQuote.TotalQueries;
                    newQuote.Comments = dailyQuote.TotalQueriesComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Total Quotes Returned";
                    newQuote.Value = dailyQuote.TotalQuotesReturned;
                    newQuote.Comments = dailyQuote.TotalQuotesReturnedComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Total Clicks";
                    newQuote.Value = dailyQuote.TotalClicks;
                    newQuote.Comments = dailyQuote.TotalClicksComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Provider Quote Rate %";
                    newQuote.Value = dailyQuote.ProviderQuoteRate;
                    newQuote.Comments = dailyQuote.ProviderQuoteRateComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Filtered Quotes";
                    newQuote.Value = dailyQuote.FilteredQuotes;
                    newQuote.Comments = dailyQuote.FilteredQuotesComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                    newQuote.QuoteType = "Top Quotes";
                    newQuote.Value = dailyQuote.TopQuotes;
                    newQuote.Comments = dailyQuote.TopQuoteComments;
                    db.DailyQuotes.Add(newQuote);
                    db.SaveChanges();

                }

                return RedirectToAction("Index");
            }


            ModelState.AddModelError("QuoteSource", "Please Select the Date");

            ViewBag.QSourceList = GetQuoteSource();
            ViewData["QSourceList"] = GetQuoteSource();
            return View(dailyQuote);
        }

             [HttpPost]
            public ActionResult GetView(string id)
            {
                if (id == "Confused" || id == "Go Compare")
                {
                DailyQuoteTable _model = new DailyQuoteTable
                {
                    QuoteSource = id
                };

                return PartialView("InsertData", _model);
                }
                else if (id == "Compare The Market")
                {
                DailyQuoteTable _model = new DailyQuoteTable
                {
                    QuoteSource = id

Views/DailyQuotes/Create.cshtml
@model DailyPerformanceReportAuto.ViewModel.DailyQuoteTable

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal ">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group col-md-12 bluebackground">
            @Html.LabelFor(model => model.QuoteSource, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.QuoteSource, (IEnumerable<SelectListItem>)ViewBag.QSourceList, new { id = "ddlSource", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QuoteSource, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}


<div id="Result" class="hidden"></div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript" src="@Url.Content("/Scripts/bootstrap.js")"></script>
    <script type="text/javascript">

        $(document).ready(function ()
        {
            $('#ddlSource').change(function ()
            {
                var _source = $("#ddlSource").val();
                if (_source == "Confused" || _source == "Go Compare")
                {
                    $.ajax(
                    {
                        url: '@Url.Action("GetView", "DailyQuotes")',
                        data: { id: _source },
                        cashe: false,
                            type: "POST",
                            dataType: "html",
                        success: function(data)
                        {
                            $('#Result').removeClass('hidden');
                            $('#Result').html(data);
                        }
                        });
                    debugger
                }
                else if (_source=="Compare The Market" || _source == "Money Supermarket")
                {
                    $.ajax(
                    {
                        url: '@Url.Action("GetView","DailyQuotes")',
                        data: { id : _source },
                        cashe: false,
                        type: "POST",
                        dataType: "html",
                        success: function (data)
                        {
                            $('#Result').removeClass('hidden');
                            $('#Result').html(data);
                        }
                    });
                }
            });
        });

        $(function ()
        {
              $('.datepicker').datepicker();
          });
    </script>
}

Views/DailyQuotes/Delete.cshtml
@model DailyPerformanceReportAuto.Models.DailyQuote

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DailyQuote</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.QuoteSource)</dt>
        <dd>@Html.DisplayFor(model => model.QuoteSource)</dd>
        <dt>@Html.DisplayNameFor(model => model.QuoteType)</dt>
        <dd>@Html.DisplayFor(model => model.QuoteType)</dd>
        <dt>@Html.DisplayNameFor(model => model.Date)</dt>
        <dd>@Html.DisplayFor(model => model.Date)</dd>
        <dt>@Html.DisplayNameFor(model => model.Value)</dt>
        <dd>@Html.DisplayFor(model => model.Value)</dd>
        <dt>@Html.DisplayNameFor(model => model.Comments)</dt>
        <dd>@Html.DisplayFor(model => model.Comments)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/DailyQuotes/Details.cshtml
@model DailyPerformanceReportAuto.Models.DailyQuote


@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DailyQuote</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.QuoteSource)</dt>
        <dd>@Html.DisplayFor(model => model.QuoteSource)</dd>
        <dt>@Html.DisplayNameFor(model => model.QuoteType)</dt>
        <dd>@Html.DisplayFor(model => model.QuoteType)</dd>
        <dt>@Html.DisplayNameFor(model => model.Date)</dt>
        <dd>@Html.DisplayFor(model => model.Date)</dd>
        <dt>@Html.DisplayNameFor(model => model.Value)</dt>
        <dd>@Html.DisplayFor(model => model.Value)</dd>
        <dt>@Html.DisplayNameFor(model => model.Comments)</dt>
        <dd>@Html.DisplayFor(model => model.Comments)</dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/DailyQuotes/Edit.cshtml
@model DailyPerformanceReportAuto.Models.DailyQuote

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>DailyQuote</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.QuoteSource, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuoteSource, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuoteSource, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuoteType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuoteType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuoteType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/DailyQuotes/Index.cshtml
@model DailyPerformanceReportAuto.Models.DailyQuote

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br /><br />
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<br /><br /><br />

@using (Html.BeginForm("IndexList", "DailyQuotes"))
{

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group col-md-12">

            <div class="col-md-4">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.QuoteSource, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.QuoteSource, (IEnumerable<SelectListItem>)ViewBag.QSourceList, htmlAttributes: new { id = "ddlSource", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.QuoteSource, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="col-md-2">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { id = "_date", @class = "form-control datepicker text-box single-line" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="col-md-2">
                <input type="button" value="Submit" id="btnSubmit" class="btn btn-primary btn-lg" />
            </div>


        </div>
    </div>

    <div id="Result">

    </div>
}

@section Scripts {


    @Scripts.Render("~/bundles/jqueryval")


    <script type="text/javascript" src="@Url.Content("/Scripts/bootstrap.js")"></script>

    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>


    <script type="text/javascript">

        $(document).ready(function () {
            $.ajax({

                url: '@Url.Action("IndexListToday", "DailyQuotes")',
                cashe: false,
                type: 'POST',
                success: function (data) {
                    $('#Result').html(data);
                }
            });



            $('#btnSubmit').click(function () {
                if ($('#_date').val() == null) {
                    alert($('#ddlSource').val());
                }
                else
                {
                    var _Qsource = $('#ddlSource').val();
                    var _dates = $('#_date').val();
                    $.ajax({
                        url: '@Url.Action("IndexList", "DailyQuotes")',
                        data: { _source: _Qsource, _datestring: _dates },
                        cashe: false,
                        type: 'POST',
                        beforeSend: function () {
                            $('#Result').html("<H1>Loading ....... </H1>");
                          //  $('#btnSubmit').prop('disabled', ture);
                        },
                        success: function(data)
                        {
                            $('#Result').html(data);
                           // $('#btnSubmit').disabled = false;
                        }

                    });
                }
            });
        });
    </script>

}

Views/DailyQuotes/_DisplayQuote.cshtml
@model  IEnumerable <DailyPerformanceReportAuto.Models.DailyQuote>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.QuoteSource)</th>
        <th>@Html.DisplayNameFor(model => model.QuoteType)</th>
        <th>@Html.DisplayNameFor(model => model.Date) </th>
        <th>@Html.DisplayNameFor(model => model.Value)</th>
        <th>@Html.DisplayNameFor(model => model.Comments)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.QuoteSource)</td>
            <td>@Html.DisplayFor(modelItem => item.QuoteType)</td>
            <td>@Html.DisplayFor(modelItem => item.Date)</td>
            <td>@Html.DisplayFor(modelItem => item.Value)</td>
            <td>@Html.DisplayFor(modelItem => item.Comments)</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>